version: '3.8'
services:
  postgres-db:
    image: postgres:17-alpine
    container_name: image-post-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagepost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: