version: '3.8'
services:
  postgres-db:
    image: postgres:17-alpine
    container_name: image-post-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagepost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: image-post:latest
    container_name: image-post
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres-db

volumes:
  postgres_data: